config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :favorites
  end
  resources :favorites
  resources :interests
  resources :articles
  resources :user_interests

  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#handle_login"
  delete "/logout", to: "users#logout"
  get "/user_interests", to: "user_interests#index"

end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :favorites
    has_many :users, through: :favorites

    def self.search(search)
        if search
            article = Article.find_by(title: search)
                if article
                    self.where(article_id: article)
                else
                    Article.all
                end
        else
            Article.all
        end
    end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :article
    validates :article_id, uniqueness: {scope: :user_id}
end

app/models/interest.rb
class Interest < ApplicationRecord
    has_many :user_interests 
    has_many :users, through: :user_interests

    # ENV["NEWS_API_KEY"]


    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :favorites
    has_many :articles, through: :favorites
    has_many :user_interests 
    has_many :interests, through: :user_interests

    validates :username, uniqueness: true 
    validates :name, uniqueness: true 
    validates :password, length: {in: 6..15, message: "Must be 6-15 characters long!"}

    has_secure_password

    def get_interests_by_name 
        self.interests.map {|interest| interest.topic}
    end

    def interested_topics
        Article.all.filter do |article| 
            get_interests_by_name.include?(article.category)
        end
    end

end

app/models/user_interest.rb
class UserInterest< ApplicationRecord
    belongs_to :user
    belongs_to :interest
    validates :interest_id, uniqueness: {scope: :user_id}
end

app/models/userinterest.rb
class Userinterest < ApplicationRecord
    belongs_to :user
    belongs_to :interest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized, :logged_in?, :set_time
    helper_method :logged_in?

    def set_time
        @time = Time.now
    end

    def set_current_user
        @current_user = User.find_by(id: session[:user])
    end

    def logged_in?
        !!set_current_user
    end

    def authorized
        redirect_to new_user_path unless logged_in?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

private
def article_params
  params.require(:article).permit(:title, :category, :source, :author, :description, :content, :publishedAt, :url, :urlToImage, :search)
end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :find_favorite, only: [:show, :edit, :update, :destroy]
  
  def index
    @favorites = @current_user.favorites

  end

  def show
  end

  def new
    @favorite = Favorite.new
  end

  def create
    favorite = @current_user.favorites.create(favorite_params)
    # byebug
    if favorite.valid?
    
      redirect_to user_path(@current_user)
    else 
      flash[:my_errors] = favorite.errors.full_messages
      redirect_to user_path(@current_user)
    end 
  end

  def edit 
    @favorite = Favorite.find(params[:id])
  end 

  def update 
    @favorite.update(favorite_params)
  
    redirect_to favorite_path(@favorite)
  end 

  def destroy 
    @favorite.destroy
    redirect_to favorites_path
    
  end 

  private 
  def find_favorite
    @favorite = Favorite.find(params[:id])
  end

  def favorite_params
    params.permit(:article_id)
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  
  private 

  def interest_params
    params.require(:interest).permit(:topic)
  end 
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController
  before_action :find_user_interest, only: [:show, :update, :edit, :destroy]

  def index
    @user_interests = @current_user.user_interests 
    @interests = Interest.all
    @articles = Article.all
  end

  def show
  end

  def new
    @user_interests = UserInterest.new
  end

  def create
    params[:user_interest].each do |ui|
      @current_user.user_interests.create(interest_id: ui[:interest_id])
    end
      redirect_to user_interests_path
  end

  def edit 
  end 

  def update 
    @user_interest.update(interest_params)
    redirect_to user_interest_path(@user_interest)
  end 

  def destroy 
    @user_interest.destroy
    redirect_to user_interests_path
  end 

  private 
  def find_user_interest
    @user_interest = UserInterest.find(params[:id])
  end

  def user_interest_params
    params.require(:user_interest).permit(:user_id, :interest_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :login, :handle_login]

  def new
    @user = User.new
  end

  def create
      @user = User.create(user_params)
      if @user.valid?
          session[:user] = @user.id
          redirect_to new_user_interest_path
      else
        flash[:my_errors] = @user.errors.full_messages
        redirect_to new_user_path
      end
  end

  def login
  end

  def handle_login
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user] = @user.id
      redirect_to user_path(@user)
    else
      flash[:my_errors] = "Incorrect Username or Password"
      redirect_to login_path
    end
  end

  def logout
      session[:user] = nil
      redirect_to login_path
  end

  private
  def user_params
      params.require(:user).permit(:username, :name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/user_interests_helper.rb
module UserInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/edit.html.erb
<h1>Update your list!</h1>

<%= form_for @favorite do |f| %>
  <%= f.label :article_id %>
  <%= f.collection_select :article_id, Article.all, :id, :title  %>

<%= f.submit %>
<% end %>

app/views/favorites/index.html.erb
<br>
<h1 style="text-align:center"> <%= @current_user.name %>'s Favorites </h1>

<ol>
    <% @current_user.favorites.each do |fav| %>
        <li>
            <%= link_to fav.article.title, favorite_path(fav), {:style=>'color:#000000;', :class => "css_class"} %>
        </li>
    <% end %>
</ol>

<!--
<%= button_to "Add Favorites", new_favorite_path, method: :get %>
-->

app/views/favorites/new.html.erb
<h1> New Favorites</h1>


<%= form_for @favorite do |f| %>
  <%= f.label :article_id %>
  <%= f.collection_select :article_id, Article.all, :id, :title  %>
<%= f.submit %>
<% end %>

app/views/favorites/show.html.erb
<br>
<div style="padding-left: 30px">
<h2><%= link_to @favorite.article.title, @favorite.article.url, {:style=>'color:#000000;', :class => "css_class"} %>
</h2>
<h2><%= @favorite.article.author %></h2>
<p>Category: <%= @favorite.article.category %></p>
<% time = @favorite.article.publishedAt = Time.new %> 
<p> Published: <%= time.strftime("%I:%M %p on %B %d") %> </p>
<p style="text-align:justified">"<%= @favorite.article.content%>"</p>
<img style="max-width: 800px;"src="<%= @favorite.article.urlToImage %>" alt="<%@favorite.article.title%>">
</div>





</p>

<br>
<div style="horizontal" class='button-horizontal'>
<%= button_to "Delete", favorite_path(@favorite), method: :delete %>  
<%= button_to "Back", favorites_path, method: :get %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
  
    <title>Flatiron Daily</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<nav style="text-align:center" class="nav navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <h1 >The Flatiron Daily</h1>
    </div>
    <div style="text-align:ceter">
        <% if logged_in? %>
          Logged in as: <%= @current_user.name %>
        <% end %>
    </div>
    <div style="horizontal" class='nav-horizontal'>
    <% if logged_in? %>
      <%= link_to "Home", "/users/show" %>
      <%= link_to "Interests", user_interests_path %>
      <%= link_to "Favorites", favorites_path %>
      <%= link_to "Sign Out", "/logout", method: :delete %>
    <% else %>
    <% end %>

    <br>
  </div>
</nav>

    <%= yield %>
  </body>
</html>



  

app/views/user_interests/edit.html.erb
<h2 style="text-align:center";> Edit Interests </h2>

<%= form_tag user_interests_path do %>
    <%= label_tag "Select Interest" %>
    <select name="user_interest[][interest_id]" > 
      <% Interest.all.each do |interest| %>
        <option value="<%= interest.id %>"> <%= interest.topic%> </option>
      <% end %>
    </select>
  <%= submit_tag %>
<% end %>

app/views/user_interests/index.html.erb
<br>
<h1 style="text-align:center"> <%= @current_user.name %>'s Interests </h1>

<ol>
    <% @current_user.user_interests.each do |user_interest| %>
        <li>
            <%= link_to user_interest.interest.topic, user_interest_path(user_interest) %>
        </li>
    <% end %>
</ol>

<%= button_to "Add Interests", new_user_interest_path, method: :get %>

app/views/user_interests/new.html.erb
<br>
<h1>What kind of news interests you?</h1>

<%= form_tag user_interests_path do %>
  <% if @current_user.user_interests.count < 1 %>
      <% 3.times do  %>
          <%= label_tag "Select Interest" %>
          <select name="user_interest[][interest_id]" > 
            <% Interest.all.each do |interest| %>
              <option value="<%= interest.id %>"> <%= interest.topic%> </option>
            <% end %>
          </select>
      <% end  %>
  <% else %>
        <%= label_tag "Select Interest" %>
        <select name="user_interest[][interest_id]" > 
          <% Interest.all.each do |interest| %>
            <option value="<%= interest.id %>"> <%= interest.topic%> </option>
          <% end %>
        </select>
  <% end %>
  <%= submit_tag %>
<% end %>

app/views/user_interests/show.html.erb
<br>
<h1 style="text-align:center"> Interest: <%= @user_interest.interest.topic %> </h1>



<%= button_to "DELETE", user_interest_path(@user_interest), method: :delete %>
<%= button_to "Back", user_interests_path, method: :get %>


<!--
<%= button_to "Edit interests", edit_user_interest_path, method: :get %>
>

app/views/users/login.html.erb
<!-- <a style="text-align:right" href="/users/new" class= "button" >Sign Up</a> -->
<br>
<h1 style="text-align:center">Hello, Please Login!</h1>
<br>

<% if flash[:my_errors]%>
    <br> <p style="color:red"><%= flash[:my_errors]%></p>
<% end %>


<%= bootstrap_form_tag url: "/login", layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f| %>
    <div class="container" width="50px"><%= f.text_field :username %></div>
    <div class="container" width="50px" ><%= f.password_field :password %></div>
    <div class="container"><%= f.submit "Log in!" %></div>
    <br>
    <a href="/users/new" class= "container" >Sign Up</a>
<% end %>

app/views/users/new.html.erb
<br>
<div>
<h1 class="center">Sign Up</h1>
</div>

<% if flash[:my_errors]%>
    <br> <p style="color:red"><%= flash[:my_errors]%></p>
<% end %>
<div class="col-xlg">

    <div align="center" class="col-md-8">
        <%= form_for @user do |f| %>
        <div class="container">
                <div class="row">
                    <div style="margin: auto" align="center">
                        <div align="center" class="form-control">
                            <div class="form-group">
                                <%= f.label :username %>
                                <%= f.text_field :username %>
                            </div>
                            <div class="form-group">
                                <%= f.label :name %>
                                <%= f.text_field :name %>
                            </div>
                            <div class="form-group">
                                <%= f.label :age %>
                                <%= f.number_field :age %>
                            </div>
                            <div class="form-group">
                                <%= f.label :password %>
                                <%= f.password_field :password %>
                            </div>
                            <div class="form-group">
                                <%= f.label :password_confirmation %>
                                <%= f.password_field :password_confirmation %>
                            </div>
                            <%= f.submit "Register" %>
                        
                    </div>
                </div>
        <% end %>
    </div>       


<br>
<div class="button">
    <a href = "/login" >back</a>
</div>

app/views/users/show.html.erb
<br>
<h1 style="text-align:center"> <%= @current_user.name %>'s Homepage </h1>
<br>


<!--
<h4 style="text-align:center"> Your Interests:
<% @current_user.interests.each do |interest| %>
    <strong><%= interest.topic %> |</strong>
<% end %>
</h4>
-->
<table class="centered highlight" style="margin: 0 50px 100px 50px">
    <thead>
        <tr>
            <th>Category</th>
            <th>Title</th>
            <th>Published At</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <% @current_user.interested_topics.each do |article| %>
        <tbody>
                <td><%= article.category %></td>
                <td style="color:#000000;"><%= link_to article.title, article.url, class: 'css_class', style: 'color:#000000', target: :_blank %> </td>
                <td><% time = article.publishedAt = Time.new %>
                <%= time.strftime("%I:%M %p on %B %d") %> </td>
                <td><img style="max-width: 200px;"src="<%= article.urlToImage %>" alt="<%article.title%>" class="index-img"></td>
                <td class="btn btn-default"> <%= button_to "Add to Favorites", "/favorites/?article_id=#{article.id}" %> </td>
            </tr>
        </tbody>
    <% end %>
</table>